### ISSUE TITLE
idisguise-full-5.6.4 Snapshot 12 crashing servers

### ISSUE THREAD

**Issue by FatherWh0** [robingrether/iDisguise#13]
I've got two servers that have been suffering crashes for several days. iDisguise gets listed in the watchdog reports. As a test I removed iDisguise from one that was crashing repeatedly. We had an event going and something about the event was causing crashes every 2 minutes. With iDisguise removed the crashes stopped. Here are a few of the watchdog reports.
https://hastebin.com/degohaxime.md
https://hastebin.com/gegihawoxe.md
https://hastebin.com/uqidumalur.md
https://hastebin.com/bugawixime.md
And from the second server:
https://hastebin.com/jonigutuva.md
Due to the number of times the first server has restarted I am leaving iDisguise unloaded until you have a chance to look things over, however the second server has not crashed today so I updated it to snapshot 14. I will let you know if there are any issues.
paper 1.12 # 1162

**Comment by luisagrether** [comment]
You may try to turn off _disguise.modify-scoreboard-packets_ in the _config.yml_. This should resolve the problem, I will however try to fix it in the first place.

**Comment by luisagrether** [comment]
You may as well try snapshot #15 (or higher). I've changed the piece of code which I thought was responsible for these crashes, but I can't test it on my own since I'm not a big server owner like you are :D

**Comment by FatherWh0** [comment]
I've had both servers running fine on # 13 with scoreboard meddling disabled. I'll update to # 15 but I see no reason to turn disguise.modify-scoreboard-packets back on. Normally I'd use my test server for such things but I never could get it to crash. I'm not sure exactly what triggered the issue to reproduce it intentionally. Any thoughts there? If so I could see about letting it meddle with the scoreboard on the test server and see what happens.

**Comment by luisagrether** [comment]
It is the scoreboard stuff that triggered the server crashes.

Detailed explanation:
Since Minecraft 1.7.9 unique account IDs are used instead of player names. This applies to both world and data storage as well as the client server communication. Unfortunately there is one aspect that server and client still communicate via player names: scoreboard teams and scores.
Some users have been complaining about my plugin messing up scoreboard features such as health bars and team prefixes. Therefore I decided to implement a feature to modify scoreboard packets when they are sent to a client. This however requires the plugin to guess every account ID from its affiliated player name. This process requires my plugin to contact Mojang's servers whenever it doesn't know a certain player name. Contacting Mojang's servers is done asynchronous of course, as it would otherwise interrupt the server thread. But on your server too many scoreboard packets are sent causing too many checks via Mojang's servers using up too much CPU time until the server is finally entirely overloaded and doesn't respond anymore (= crash).

In the latest snapshots, scoreboard packets are only modified as long as the plugin has all necessary player name -> account ID mappings available locally. No contact to Mojang's servers is established and the server will never overload. No matter if you're using this feature or not.

**Comment by FatherWh0** [comment]
Makes sense. I've set modify-scoreboard-packets: true with build # 15. I'll let you know if there's any issues.

**Comment by luisagrether** [comment]
Finally, you may switch to the official release (5.6.4) now. I think you didn't notice any issues so far :D

https://www.spigotmc.org/resources/idisguise.5509/
