### ISSUE TITLE
[Suggestion] Consider moving to a netty channel handler instead of overwriting the player connection

### ISSUE THREAD

**Issue by I-Al-Istannen** [robingrether/iDisguise#21]
## Issue
You are currently overwriting the player connection, which caused me some neglectable pain, but might impact compatibility with other plugins too.

## Possible mitigation
Judging by the 1.12 specific code, the only real changes you made were listening for some packets and providing a different way to send a packet. Listening and modifying packets can be done with a ChannelDuplexHandler (or just one way, if that's enough) in a matter that should preserve compatibility with other plugins, as netty listeners can be chained and do not replace each other. Packet sending can be done with a vanilla PlayerConnection, so you would only need to move the helper delegation methods (e.g. to a utility class).

## Possible problems with this approach
I haven't looked at much more of your codebase as the nms-version specific parts, so it could be entirely possible that you have very strong reasons to take the approach you took. I sadly didn't have the time to look into it more deeply, so please consider this strictly a *possible **suggestion***.

**Comment by luisagrether** [comment]
Actually, I took this approach (Netty duplex handler) in the past. However, Netty is run asynchronous with the main thread. While asynchronous execution improves network performance, it limits Bukkit API access and a lot more.

At the moment, my approach in order to disguise players is to create as few packets as possible. To accomplish this, I use Bukkit's showPlayer/hidePlayer functionality to create the packets. All iDisguise then does is modify them in the correct way to create a disguise. This approach is relatively easy, since I only need the code to edit packets.
However, this approach requires synchronization between packet editting and disguising. Thus I have to edit the packets synchronous with the main thread which means I can't use Netty. This is why I replace the player connections.

**Comment by luisagrether** [comment]
If you have an idea to solve this synchronization problem, I would be absolutely willing to make the necessary changes to my plugin in order to use the Netty channel handlers.

**Comment by I-Al-Istannen** [comment]
You mean inside your PacketHandler (`public static Object[] handlePacketOut(final Player observer, final Object packet) {`)?

I can't seem to find many more references to the player connection and this is what is called when you send a packet through the custom one.

**Comment by luisagrether** [comment]
I think I have found a way to move to a Netty channel handler.
I'm going to test this as soon as I have time for it.

**Comment by luisagrether** [comment]
iDisguise 5.8.1 now uses a Netty channel handler. And if ProtocolLib is present on the server it edits packets via a packet listener.

**Comment by I-Al-Istannen** [comment]
Thank you for your work and enjoy your day! :)
