### ISSUE TITLE
New 1.13 fish

### ISSUE THREAD

**Issue by x1p** [robingrether/iDisguise#23]
Couple of questions regarding the odd behavior of the 1.13 fish

First of all, they are not on the wiki yet. Not a priority off course.

On land, the players appear on their side. So the fish is flat on land. I suppose this is normal behavior, so I ask just to be sure if this is intended.

Another player can scoop the fish (disguised player) with its bucket. The disguised player disappears for him. So the disguised player is totally invisible for him. A third player, watching these two players, can see the disguised player fine.
When the player, who caught the disguise player, goes offline (or lobby), and comes back, the disguised player is undisguised for the player who caught the "fish".

**Comment by luisagrether** [comment]
The bucket behavior is definitely not intended and will therefore be fixed as soon as possible.

The side appearance is a result of how Minecraft renders fish on land. If possible, I can add an option to change this either in the plugin configuration or separately for each disguise as a subtype.

Last but not least the wiki ... well 1.13.1 support is still in Beta due to the fact that I was too busy the last two months. Thus I didn't have time to update the wiki either.

I will have more time the next weeks, so you can expect both a plugin update as well as an updated wiki shortly.

**Comment by x1p** [comment]
Awsome

**Comment by luisagrether** [comment]
The bucket behavior is fixed now. The side appearance however cannot be changed.

You can try it out: [iDisguise 5.8.1-SNAPSHOT #57](http://repo.robingrether.de/de/robingrether/idisguise/idisguise-full/5.8.1-SNAPSHOT/idisguise-full-5.8.1-20181010.223033-57.jar)

**Comment by x1p** [comment]
Works fine. Thanks
