### ISSUE TITLE
Permission Nodes

### ISSUE THREAD

**Issue by Muffin-101** [robingrether/iDisguise#40]
I cant find the permission nodes. I kinda need them for a server. Could someone please tell me them?

**Comment by luisagrether** [comment]
I'm sorry. In January, I took my website (including the iDisguise Wiki) down because I thought nobody would need it anymore now that I discontinued this project. However, on your request, it is again available as of today. You find the permission nodes here: [https://www.robingrether.de/idisguise/wiki/permissions/](https://www.robingrether.de/idisguise/wiki/permissions/)
